# Generated by Django 3.2 on 2021-05-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210522_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
