# Generated by Django 3.2 on 2021-05-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_colaborador_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
