# Generated by Django 3.2 on 2021-06-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productoimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoImage',
        ),
    ]
